"""init contact + call_activity

Revision ID: 38d058b11477
Revises: 
Create Date: 2026-05-27 13:57:05.814886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '38d058b11477'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_name_norm', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name_norm', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_first_name_norm'), 'contact', ['first_name_norm'], unique=False)
    op.create_index(op.f('ix_contact_last_name_norm'), 'contact', ['last_name_norm'], unique=False)
    op.create_table('callactivity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('caller_first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('caller_last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('callactivity')
    op.drop_index(op.f('ix_contact_last_name_norm'), table_name='contact')
    op.drop_index(op.f('ix_contact_first_name_norm'), table_name='contact')
    op.drop_table('contact')
    # ### end Alembic commands ###
